# Generated by Django 3.1.7 on 2021-03-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=20, verbose_name='Banco')),
                ('codigo', models.CharField(max_length=4, verbose_name='Codigo')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=80, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Centro_de_Custo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroDeCusto', models.CharField(max_length=80, verbose_name='Centro de Custo')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Departamento')),
                ('codigo', models.CharField(default='', max_length=8, verbose_name='Codigo Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Informacao_Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=4, verbose_name='Agencia')),
                ('cc', models.CharField(max_length=7, verbose_name='C/C')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beneficio.banco', verbose_name='Banco')),
            ],
        ),
        migrations.CreateModel(
            name='Informacoes_Escala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala', models.CharField(max_length=20, verbose_name='Escala')),
                ('horarioInicial', models.TimeField(auto_now=True, verbose_name='Horario Inicio')),
                ('horarioFinal', models.TimeField(auto_now=True, verbose_name='Horario Final')),
                ('diasPorSemana', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='salario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Base')),
                ('adicional_tipo', models.CharField(default='', max_length=20, verbose_name='Adicional (Tipo)')),
                ('adicional_valor', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Adicional (Valor)')),
                ('desconto_VT', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Desconto VT')),
                ('desconto_VR', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Desconto VR')),
                ('desconto_VA', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Desconto VA')),
                ('adiantamento', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Adiantamento')),
                ('liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Liquido')),
                ('comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Comissão')),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Bonus')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCompleto', models.CharField(max_length=80, verbose_name='Profissional')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('base', models.CharField(max_length=30, verbose_name='Base')),
                ('contato', models.CharField(blank='True', max_length=11, null='True', verbose_name='Contato')),
                ('matricula', models.CharField(max_length=6, verbose_name='Matricula')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beneficio.departamento', verbose_name='Novo Departamento')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beneficio.empresa_cliente', verbose_name='Cliente')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beneficio.cargo', verbose_name='Cargo')),
                ('informacao_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficio.informacao_pagamento', verbose_name='Informações para Pagamento')),
                ('salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficio.salario', verbose_name='Salario')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(auto_now=True, verbose_name='Inicio')),
                ('termino', models.DateField(auto_now=True, null=True, verbose_name='Termino')),
                ('tempoInicial', models.PositiveIntegerField(default=30)),
                ('prorrogacao', models.PositiveIntegerField(default=0)),
                ('limiteContratacao', models.PositiveIntegerField(default=240)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficio.profissional', verbose_name='Profissional')),
            ],
        ),
    ]
