# Generated by Django 3.1.7 on 2021-03-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0002_auto_20210321_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoes_escala',
            name='horarioFinal',
            field=models.TimeField(auto_now_add=True, verbose_name='Horario Final'),
        ),
        migrations.AlterField(
            model_name='informacoes_escala',
            name='horarioInicial',
            field=models.TimeField(auto_now_add=True, verbose_name='Horario Inicio'),
        ),
    ]
