# Generated by Django 3.1.7 on 2021-03-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0004_auto_20210321_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='inicio',
            field=models.DateField(auto_created=True, verbose_name='Inicio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='termino',
            field=models.DateField(auto_created=True, blank=True, null=True, verbose_name='Termino'),
        ),
    ]
