# Generated by Django 3.1.7 on 2021-03-22 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0005_auto_20210322_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia_de_Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adiantamento', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Adiantamento')),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Comissão')),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Bônus')),
                ('salario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficio.salario', verbose_name='Salario')),
            ],
        ),
    ]
