# Generated by Django 3.1.7 on 2021-03-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficio', '0007_auto_20210322_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dia_de_pagamento',
            name='salario',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='limiteContratacao',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tempoInicial',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='dia_de_pagamento',
            name='adiantamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Adiantamento'),
        ),
        migrations.AlterField(
            model_name='dia_de_pagamento',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Bônus'),
        ),
        migrations.AlterField(
            model_name='dia_de_pagamento',
            name='comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='salario',
            name='adiantamento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Adiantamento'),
        ),
        migrations.AlterField(
            model_name='salario',
            name='adicional_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Adicional (Valor)'),
        ),
        migrations.AlterField(
            model_name='salario',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='salario',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Comissão'),
        ),
        migrations.AlterField(
            model_name='salario',
            name='desconto_VA',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Desconto VA'),
        ),
        migrations.AlterField(
            model_name='salario',
            name='desconto_VR',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Desconto VR'),
        ),
        migrations.AlterField(
            model_name='salario',
            name='desconto_VT',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Desconto VT'),
        ),
        migrations.AlterField(
            model_name='salario',
            name='liquido',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Liquido'),
        ),
    ]
